server:
  port: 8083

spring:
  application:
    name: ms-reserva

  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:3306/db_hotel_reserva?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:holaflan}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  web:
    error:
      include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  server-url: http://localhost:8080