server:
  port: 8080 # El puerto principal del hotel

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        # Ruta para tu ms-auth
        - id: auth-service
          uri: lb://ms-auth
          predicates:
            - Path=/api/usuarios/**

        # Ruta para el ms-habitacion (El de Alejandra)
        - id: habitacion-service
          uri: lb://ms-habitacion
          predicates:
            - Path=/api/habitaciones/**

        # Ruta para el ms-reserva (El de Anaís)
        - id: reserva-service
          uri: lb://ms-reserva
          predicates:
            - Path=/api/reservas/**

        # Ruta para el ms-facturacion (El de Anaís)
        - id: facturacion-service
          uri: lb://ms-facturacion
          predicates:
            - Path=/api/facturas/**

# ==========================================
# CONFIGURACIÓN DE EUREKA CLIENT
# ==========================================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true