server:
  port: 8082

spring:
  application:
    name: ms-habitacion

  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:3306/db_hotel_habitacion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:holaflan}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true

ms:
  reserva:
    url: http://${MS_RESERVA_HOST:host.docker.internal}:8083

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  server-url: http://localhost:8080